#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations --noinput
python manage.py migrate
python manage.py collectstatic --noinput
exec gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 10.10.0.101:8000
