# Generated by Django 5.1.9 on 2025-05-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0002_question_alter_examevent_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='roll_number_end',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='roll_number_start',
        ),
    ]
