# Generated by Django 5.1.9 on 2025-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0003_remove_examsession_roll_number_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='roll_number_end',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examsession',
            name='roll_number_start',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
