# Generated by Django 5.1.9 on 2025-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0004_examsession_roll_number_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='exam_ended_at',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='exam_started_at',
        ),
        migrations.AddField(
            model_name='examsession',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='Time_Remaining',
            field=models.IntegerField(default=0),
        ),
    ]
