# Generated by Django 5.1.9 on 2025-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0005_remove_exam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
