# Generated by Django 5.1.9 on 2025-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0006_alter_examsession_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='end_time',
            field=models.DateField(null=True),
        ),
    ]
