# Generated by Django 5.1.9 on 2025-05-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0008_alter_examsession_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='hall_allocation',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='hall_allocation',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='roll_number_end',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='roll_number_start',
        ),
        migrations.CreateModel(
            name='HallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number_range', models.CharField(help_text='Format: MG12XX10 - MG12XX20', max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExam.hall')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_assignments', to='appExam.examsession')),
            ],
        ),
        migrations.AddField(
            model_name='questionset',
            name='hall_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='appExam.hallassignment'),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='hall_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExam.hallassignment'),
        ),
        migrations.DeleteModel(
            name='HallAllocation',
        ),
    ]
