# Generated by Django 5.1.9 on 2025-06-01 09:42

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0009_remove_studentexamenrollment_hall_allocation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HallAssignment',
            new_name='HallAndStudentAssignment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_set',
        ),
        migrations.AddField(
            model_name='examsession',
            name='notice',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Notice for the exam session, can include instructions or important information.'),
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExam.examsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='question_order',
            field=models.JSONField(default=list, help_text='Stores the order of question IDs assigned to the student.'),
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
