# Generated by Django 5.1.9 on 2025-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0011_alter_question_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='Time_Remaining',
            field=models.IntegerField(default=15),
        ),
    ]
