# Generated by Django 5.1.9 on 2025-06-03 10:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0013_question_unique_session_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='answer_order',
            field=models.JSONField(default=dict, help_text="Maps each question_id (as string) to a randomized list of Answer IDs. e.g. { '632': [57, 43, 89, 61], '633': [102, 99, 105] }"),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='notice',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Notice for the exam session, can include            instructions or important information.'),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='question_order',
            field=models.JSONField(default=list, help_text='Randomized list of question IDs assigned to this student.'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='appExam.studentexamenrollment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='appExam.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appExam.answer')),
            ],
            options={
                'unique_together': {('enrollment', 'question')},
            },
        ),
    ]
