# Generated by Django 5.1.9 on 2025-06-04 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0014_studentexamenrollment_answer_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='Time_Remaining',
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='time_remaining',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Time remaining for this student in the exam session.'),
        ),
    ]
