# Generated by Django 5.1.9 on 2025-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0015_remove_studentexamenrollment_time_remaining_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status', 'start_time'], name='appExam_exa_status_2f3116_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['enrollment', 'question'], name='appExam_stu_enrollm_fbeb35_idx'),
        ),
    ]
