# Generated by Django 5.1.9 on 2025-06-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0016_examsession_appexam_exa_status_2f3116_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('submitted', 'Submitted')], default='inactive', max_length=20),
        ),
    ]
