# Generated by Django 5.1.9 on 2025-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0017_studentexamenrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
