# Generated by Django 5.1.9 on 2025-06-14 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0019_studentexamenrollment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='expected_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='total_pause_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='total_pause_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
