# Generated by Django 5.1.9 on 2025-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0020_examsession_expected_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
