# Generated by Django 5.1.9 on 2025-06-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0021_studentexamenrollment_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
