# Generated by Django 5.1.9 on 2025-06-14 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0022_alter_examsession_expected_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='pause_started_at',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='total_pause_duration',
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='active_exam_time_used',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='last_active_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
