# Generated by Django 5.1.9 on 2025-06-14 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0023_remove_studentexamenrollment_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='time_remaining',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Total time allocated for this student in the exam session.'),
        ),
    ]
