# Generated by Django 5.1.9 on 2025-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0024_alter_studentexamenrollment_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='present',
            field=models.BooleanField(default=False, help_text='Is student currently connected via WebSocket?'),
        ),
    ]
