# Generated by Django 5.1.9 on 2025-06-14 16:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0025_studentexamenrollment_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='notice',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Notice for the exam session, can include instructions or important information.'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
    ]
