# Generated by Django 5.1.9 on 2025-06-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0026_alter_examsession_notice_alter_examsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='time_remaining_at_pause',
            field=models.DurationField(blank=True, help_text='Time remaining when the exam was paused. Used to display consistent time during pause.', null=True),
        ),
    ]
