# Generated by Django 5.1.9 on 2025-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0027_studentexamenrollment_time_remaining_at_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='time_remaining_at_pause',
            field=models.DurationField(blank=True, help_text='Time remaining when the exam was paused.', null=True),
        ),
    ]
