# Generated by Django 5.1.9 on 2025-06-16 16:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0028_alter_studentexamenrollment_time_remaining_at_pause'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examsession',
            name='appExam_exa_status_2f3116_idx',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='expected_end_time',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='pause_started_at',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='total_pause_duration',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='active_exam_time_used',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='hall_assignment',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='last_active_timestamp',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='time_remaining',
        ),
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='time_remaining_at_pause',
        ),
        migrations.AddField(
            model_name='examsession',
            name='base_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name='examsession',
            name='base_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='pause_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='total_paused',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='connection_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='individual_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='answer_order',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='question_order',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='appExam.examsession'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status', 'base_start'], name='appExam_exa_status_a3f88a_idx'),
        ),
    ]
