# Generated by Django 5.1.9 on 2025-06-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0029_remove_examsession_appexam_exa_status_2f3116_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='hall_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='appExam.hallandstudentassignment'),
        ),
    ]
