# Generated by Django 5.1.9 on 2025-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0030_studentexamenrollment_hall_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
