# Generated by Django 5.1.9 on 2025-06-16 21:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0031_studentexamenrollment_session_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='notice',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Important instructions or notices for the exam session', null=True),
        ),
    ]
