# Generated by Django 5.1.9 on 2025-06-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0033_studentexamenrollment_total_paused_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='total_paused_duration',
        ),
    ]
