# Generated by Django 5.1.9 on 2025-06-19 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0034_remove_studentexamenrollment_total_paused_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='total_paused_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
