# Generated by Django 5.1.9 on 2025-06-25 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0035_studentexamenrollment_total_paused_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamenrollment',
            name='total_paused_duration',
        ),
        migrations.AddField(
            model_name='question',
            name='weightage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='paused_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
