# Generated by Django 5.1.9 on 2025-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0036_remove_studentexamenrollment_total_paused_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamenrollment',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamenrollment',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('paused', 'Paused'), ('submitted', 'Submitted')], default='inactive', max_length=20),
        ),
    ]
