# Generated by Django 5.1.9 on 2025-06-26 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0037_studentexamenrollment_paused_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='weightage',
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='individual_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamenrollment',
            name='individual_paused_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
