# Generated by Django 5.1.9 on 2025-06-27 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0038_remove_question_weightage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignment', to='appExam.studentexamenrollment')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExam.hall')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExam.examsession')),
            ],
            options={
                'indexes': [models.Index(fields=['hall', 'seat_number'], name='appExam_sea_hall_id_f3658e_idx')],
            },
        ),
    ]
