# Generated by Django 5.1.9 on 2025-06-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0039_seatassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='session_base_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(fields=('hall', 'seat_number', 'session_base_start'), name='unique_seat_per_time'),
        ),
    ]
