# Generated by Django 5.1.9 on 2025-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0013_user_token_version'),
        ('appExam', '0040_seatassignment_session_base_start_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentexamenrollment',
            index=models.Index(fields=['status', 'session'], name='appExam_stu_status_015f55_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamenrollment',
            index=models.Index(fields=['session_started_at', 'status'], name='appExam_stu_session_5e0ab2_idx'),
        ),
    ]
