# Generated by Django 5.1.9 on 2025-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0041_studentexamenrollment_appexam_stu_status_015f55_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallandstudentassignment',
            name='roll_number_range',
            field=models.TextField(help_text='Enter one or more roll number ranges, e.g., MG12XX10 - MG12XX20'),
        ),
    ]
