volumes:
  backend_local_postgres_data: {}
  backend_local_postgres_data_backups: {}
  backend_local_redis_data: {}
  backend_local_minio_data: {}
  backend_local_grafana_data: {}
  static_volume:
  media_volume:


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    container_name: backend_local_django
    network_mode: "host" # Added for host networking
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/backend/media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,10.10.0.101,django
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    image: backend_local_nginx
    container_name: backend_local_nginx
    network_mode: "host" # Added for host networking
    depends_on:
      - django
    volumes:
      - ./frontend/dist:/app/frontend:ro
      - static_volume:/app/backend/static:ro
      - media_volume:/app/backend/media:ro
      - ./compose/local/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_logs:/var/log/nginx

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    container_name: backend_local_postgres
    network_mode: "host" # Added for host networking
    volumes:
      - backend_local_postgres_data:/var/lib/postgresql/data
      - backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: backend_local_redis
    network_mode: "host" # Added for host networking
    volumes:
      - backend_local_redis_data:/data

  celeryworker:
    <<: *django
    image: backend_local_celeryworker
    container_name: backend_local_celeryworker
    network_mode: "host" # Added for host networking
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: backend_local_celerybeat
    container_name: backend_local_celerybeat
    network_mode: "host" # Added for host networking
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: backend_local_flower
    container_name: backend_local_flower
    network_mode: "host" # Added for host networking
    command: /start-flower

  minio:
    image: minio/minio:latest
    container_name: backend_local_minio
    network_mode: "host" # Added for host networking
    volumes:
      - backend_local_minio_data:/data
    env_file:
      - ./.envs/.local/.django
    command: server /data --console-address ":9001"

  prometheus:
    image: prom/prometheus:latest
    container_name: backend_local_prometheus
    network_mode: "host" # Added for host networking
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: backend_local_grafana
    network_mode: "host" # Added for host networking
    env_file:
      - ./.envs/.local/.django
    volumes:
      - backend_local_grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: backend_local_node_exporter
    network_mode: "host" # Added for host networking
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: backend_local_cadvisor
    network_mode: "host" # Added for host networking
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  locust:
    image: locustio/locust:latest
    container_name: backend_local_locust
    network_mode: "host" # Added for host networking
    depends_on:
      - django
    volumes:
      - ./compose/local/locust:/mnt/locust
    working_dir: /mnt/locust
    command:
      - -f
      - locustfile.py
      - --host=http://10.10.0.101:8000 # Updated to use IP
      - --web-port=8089
    env_file:
      - ./.envs/.local/.django
