volumes:
  backend_production_postgres_data: {}
  backend_production_postgres_data_backups: {}
  backend_production_redis_data: {}
  backend_production_minio_data: {}
  backend_production_grafana_data: {}
  static_volume:
  media_volume:


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: backend_production_django
    container_name: backend_production_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/backend/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - '8000:8000'
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: backend_production_nginx
    container_name: backend_production_nginx
    depends_on:
      - django
    volumes:
      - ./frontend/dist:/app/frontend:ro
      - static_volume:/app/backend/static:ro
      - media_volume:/app/backend/media:ro
      - ./compose/production/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    container_name: backend_production_postgres
    volumes:
      - backend_production_postgres_data:/var/lib/postgresql/data
      - backend_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6
    container_name: backend_production_redis
    volumes:
      - backend_production_redis_data:/data

  celeryworker:
    <<: *django
    image: backend_production_celeryworker
    container_name: backend_production_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: backend_production_celerybeat
    container_name: backend_production_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: backend_production_flower
    container_name: backend_production_flower
    ports:
      - '5555:5555'
    command: /start-flower

  minio:
    image: minio/minio:latest
    container_name: backend_production_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - backend_production_minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"

  prometheus:
    image: prom/prometheus:latest
    container_name: backend_production_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: backend_production_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_ROOT_URL=http://productionhost/monitor/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=productionhost
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - backend_production_grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: backed_production_node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: backend_production_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    # ───────────────────  Locust  ───────────────────
  locust:
    image: locustio/locust:latest
    container_name: backend_production_locust
    depends_on:
      - django
    volumes:
      - ./compose/production/locust:/mnt/locust
    working_dir: /mnt/locust
    command:
      - -f
      - locustfile.py
      - --host=http://django:8000
      - --web-port=8089
    ports:
      - "8089:8089"
    environment:
      - LOCUST_USER=debug
      - LOCUST_PASSWORD=debug
