# Generated by Django 5.1.9 on 2025-05-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, upload_to='institutes/photos/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='appInstitutions.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_years', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='appInstitutions.institute')),
                ('subjects', models.ManyToManyField(blank=True, related_name='programs', to='appInstitutions.subject')),
            ],
        ),
    ]
