# Generated by Django 5.1.9 on 2025-06-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0002_institute_address_institute_logo_institute_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration_years',
        ),
    ]
