# Generated by Django 5.1.9 on 2025-06-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0004_alter_program_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='appInstitutions.institute'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='institute',
            field=models.ForeignKey(help_text="if created from program, institute defaults to Program's institute", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='appInstitutions.institute'),
        ),
    ]
