# Generated by Django 5.1.9 on 2025-06-01 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0005_alter_program_institute_alter_subject_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='institute',
            field=models.ForeignKey(blank=True, help_text="if created from program, institute defaults to Program's institute", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='appInstitutions.institute'),
        ),
    ]
