# Generated by Django 5.1.9 on 2025-06-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0006_alter_subject_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='institute',
            field=models.ForeignKey(blank=True, help_text="If created from program, institute defaults to Program's institute", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='appInstitutions.institute'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('code', 'institute'), name='unique_subject_code_per_institute'),
        ),
    ]
