# Generated by Django 5.1.9 on 2025-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0007_alter_subject_code_alter_subject_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the program, e.g., BCA-2023', max_length=50),
        ),
    ]
