# Generated by Django 5.1.9 on 2025-06-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0008_program_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.CharField(help_text='Unique identifier for the program, e.g., 2023', max_length=50),
        ),
    ]
