# Generated by Django 5.1.9 on 2025-06-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInstitutions', '0009_alter_program_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='show_student_submissions',
            field=models.BooleanField(default=False, help_text='If enabled, students can see their own answers after submissions'),
        ),
    ]
