# Generated by Django 5.1.9 on 2025-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0002_celerytask_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_template', models.FileField(blank=True, null=True, upload_to='utility_files/candidate_template/')),
            ],
        ),
    ]
