# Generated by Django 5.1.9 on 2025-06-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0003_utilityfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilityFiles',
        ),
    ]
