# Generated by Django 5.1.9 on 2025-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0005_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('request_data', models.TextField()),
                ('response_data', models.TextField()),
            ],
        ),
    ]
