# Generated by Django 5.1.9 on 2025-07-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0006_apilog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='celerytask',
            index=models.Index(fields=['task_id'], name='appCore_cel_task_id_8b8378_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytask',
            index=models.Index(fields=['status', 'created'], name='appCore_cel_status_567c72_idx'),
        ),
    ]
