# Generated by Django 5.1.9 on 2025-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exam_status',
            field=models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('completed', 'Completed')], default='absent', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
