# Generated by Django 5.1.9 on 2025-06-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0002_candidate_exam_status_candidate_verification_status'),
        ('appInstitutions', '0007_alter_subject_code_alter_subject_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='appInstitutions.institute'),
        ),
    ]
