# Generated by Django 5.1.9 on 2025-06-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0003_candidate_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='generated_password',
        ),
    ]
