# Generated by Django 5.1.9 on 2025-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0004_remove_candidate_generated_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='generated_password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
