# Generated by Django 5.1.9 on 2025-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0005_candidate_generated_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='generated_password',
            field=models.CharField(max_length=128),
        ),
    ]
