# Generated by Django 5.1.9 on 2025-06-15 08:48

import appAuthentication.utils.upload_to_institute
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0007_candidate_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=appAuthentication.utils.upload_to_institute.image_upload_to_institute),
        ),
    ]
