# Generated by Django 5.1.9 on 2025-06-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0008_alter_candidate_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fingerprint_left',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fingerprint_right',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/'),
        ),
    ]
