# Generated by Django 5.1.9 on 2025-06-17 07:08

import appAuthentication.utils.upload_to_institute
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0009_candidate_fingerprint_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='fingerprint_left',
            field=models.ImageField(blank=True, null=True, upload_to=appAuthentication.utils.upload_to_institute.fingerprint_upload_to_institute),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fingerprint_right',
            field=models.ImageField(blank=True, null=True, upload_to=appAuthentication.utils.upload_to_institute.fingerprint_upload_to_institute),
        ),
    ]
