# Generated by Django 5.1.9 on 2025-06-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0010_alter_candidate_fingerprint_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='verification_notes',
            field=models.CharField(blank='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_status',
            field=models.CharField(choices=[('absent', 'Absent'), ('present', 'Present')], default='absent', max_length=10),
        ),
    ]
