# Generated by Django 5.1.9 on 2025-06-20 05:53

import appAuthentication.utils.upload_to_institute
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0011_candidate_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='initial_image',
            field=models.ImageField(blank=True, null=True, upload_to=appAuthentication.utils.upload_to_institute.image_upload_to_institute),
        ),
    ]
