# Generated by Django 5.1.9 on 2025-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0013_user_token_version'),
        ('appInstitutions', '0010_institute_show_student_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='admit_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob_nep',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_processing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='generated_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='program',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='program_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='verification_notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['symbol_number'], name='appAuthenti_symbol__4ee226_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['institute', 'symbol_number'], name='appAuthenti_institu_0bfc03_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['verification_status'], name='appAuthenti_verific_ec4522_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['exam_status'], name='appAuthenti_exam_st_eff1ae_idx'),
        ),
    ]
