# Generated by Django 5.1.9 on 2025-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0014_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='program_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
