# Generated by Django 5.1.9 on 2025-07-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0015_alter_candidate_program_id'),
        ('appInstitutions', '0010_institute_show_student_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='appInstitutions.institute'),
        ),
    ]
