# Generated by Django 5.1.9 on 2025-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuthentication', '0016_alter_candidate_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='generated_password',
            field=models.CharField(max_length=128),
        ),
    ]
